### ISSUE TITLE
Implicit use of weak pointers causing memory issues

### ISSUE THREAD

**Issue by pmlodawski** [atzeus/HMap#5]
Hi!
Why is this library using weak pointers, from key to value? 

When we add values to a map, there is no option to remove them from memory and they are stuck there until the key is deleted too. There are many use cases that you cannot remove the key (e.g updating value in a map) and need your app not too eat all the RAM.

**Comment by atzeus** [comment]
This library is using weak pointers because if the key is dead, then there is no way to retrieve the value, and hence this value is dead too. This ensures that we do not have elements in the map which are not accessible, which would be a memory leak.

 If you want to remove a value while retaining the key, use delete.

Does that answer your question, or do you have a particular use case where this causes memory issues?

**Comment by pmlodawski** [comment]
`delete` removes value from the map but this value remain in memory as long as key is available somewhere - possibly forever. That is a problem because you cannot effectively update values in HMap without using larger and larger ammounts of memory.

To have better control on values in `HMap` you can add interface which allow to delete items from map using `Unique` extracted from keys. (I added it on my fork, but it is not ready to merge yet - I need more time to clean the code)

**Comment by atzeus** [comment]
I'm confused. Why would the value remain in memory if you delete it from the map? Do you have an example demonstrating this problem? Thanks!

**Comment by pmlodawski** [comment]
This is the way weak pointers work, they keep value alive until key is alive. From the <a href=http://hackage.haskell.org/package/base-4.8.1.0/docs/System-Mem-Weak.html>official documentation</a>:

> In general terms, a weak pointer is a reference to an object that is not followed by the garbage collector - that is, the existence of a weak pointer to an object has no effect on the lifetime of that object.

See also below code

``` haskell
{-# LANGUAGE OverloadedStrings #-}

module Main where

import qualified Control.Concurrent               as Concurrent
import           Control.Monad                    (void)
import           Control.Monad.IO.Class           (liftIO)
import           Control.Monad.Trans.State.Strict
import qualified Data.HKey                        as HKey
import qualified Data.HMap                        as HMap
import           Data.Maybe                       (fromJust)
import           System.Mem                       (performGC)
import           System.Remote.Monitoring         (forkServer)


stage x msg = liftIO $ do
    putStrLn ("Stage " ++ show x ++ " - " ++ msg)
    performGC
    Concurrent.threadDelay 3000000


main = do
    forkServer "localhost" 8000
    void $ flip runStateT HMap.empty $ do
        key1 <- liftIO HKey.createKey
        _    <- liftIO HKey.createKey
        -- let key = 1
        stage 1 "HMap is empty"
        modify (HMap.insert key1 [1..10000000])
        liftIO . print . last . fromJust . HMap.lookup key1 =<< get
        stage 2 "Adding first value"
        modify (HMap.insert key1 [1..10000000])
        liftIO . print . last . fromJust . HMap.lookup key1 =<< get
        stage 3 "Updating a value - both values are still in memory"
        modify (HMap.delete key1)
        modify (HMap.insert key1 [1..10000000])
        liftIO . print . last . fromJust . HMap.lookup key1 =<< get
        stage 4 "Updating a value again - three values are in memory"
        modify (HMap.delete key1)
        stage 5 "Deleting does not remove it from memory"
        liftIO . print . HMap.lookup key1 =<< get
        stage 6 "Key is no longer alive - memory is cleaned"
```

When you open <a href=http://localhost:8000>http://localhost:8000</a> you will see the following

![mem](https://cloud.githubusercontent.com/assets/5347572/9351421/7fdc68fa-4659-11e5-8b01-1741fdaf6257.png)

As you can see, all values which have ever been added to a map are kept until key is alive, even they are no longer needed

**Comment by atzeus** [comment]
Thanks for this. You're absolutely right.

The confusion was that I thought weak references where alive iff:
(1): The key is still alive
AND
(2): The weak reference itself is alive (i.e. reachable from root set)

In that case, the use of weak references would have solved a memory leak (values for which the key is dead are also dead).

However, you are correct in observing that the actual behavior of weak references is that they are alive iff:
(1): The key is still alive.

In this case, the use of weak references does not solve a memory leak, but introduces one :( As you say: the key keeps all values alive.

I'm a bit puzzeled as to why the behavior of weak references is the latter, instead of the former, which seems more logical to me. Is this a possible improvement to weak references or would the behavior I thought it was be bad in other cases?

The most obvious fix, in the short term, is to simply remove the weak references from HMap, which I propose I do. Do you agree?

**Comment by pmlodawski** [comment]
I tried to fix it somehow and invalidate weak pointers on `delete` and `update` using `System.Mem.Weak.finalize` but it simply does not work. Calling `finalize`  make more problems - if you copy a map, and later `delete` value from one and `finalize` it values in both maps are invalidated.

Finally I decided to remove `Weak` pointers completely (https://github.com/atzeus/HMap/pull/8) and introduce some functions to manage easier values in a map (https://github.com/atzeus/HMap/pull/7)

**Comment by atzeus** [comment]
I think the only real fix would be to change the behavior of weak references to the behavior I thought they had :( I've created a ticket: https://ghc.haskell.org/trac/ghc/ticket/10780#ticket

**Comment by atzeus** [comment]
Simon Marlow responded to the ticket, it turns out it is possible to get the behavior we want. See http://research.microsoft.com/apps/pubs/default.aspx?id=67497 
I can implement this (when I get around to it), or do you want to? :)

**Comment by pmlodawski** [comment]
I think I'll not find enough time now, but it looks interesting and useful :)

**Comment by atzeus** [comment]
Finally got around to uploading your changes. Cheers!

**Comment by pmlodawski** [comment]
Thanks! :)
